[project]
name = "holistic-health-hub"
version = "0.1.0"
description = "A holistic health and fitness tracker using Drafter and the Gemini API."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "coverage",
    "drafter",
    "bakery",
    "pylint",
    "mypy",
    "matplotlib",
    "pillow",
    "analyze_drafter_site",
    # new dependencies for gemini and state
    "google-genai",
    "python-dotenv",
    "pydantic",
]

[tool.pyright]
reportWildcardImportFromLibrary = "none"


[tool.ruff]
line-length = 120
